{{- if .Values.gateway.enabled -}}
{{- $serviceName := include "proxy.name" . -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "proxy.name" . }}
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName | quote }}
  listeners:
    - name: {{ .Values.gateway.listener.name }}
      protocol: {{ .Values.gateway.listener.protocol }}
      port: {{ .Values.gateway.listener.port }}
      allowedRoutes:
        namespaces:
          from: All

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "proxy.name" . }}-http
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ include "proxy.name" . }}
  hostnames:
    {{- range .Values.gateway.hosts }}
    - {{ . | quote }}
    {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ $serviceName }}
          port: {{ $.Values.service.port }}
          weight: 1
{{- end }}
