apiVersion: v2
appVersion: "1.0.0"
description: A Helm chart for Ingress with ExternalName
icon: https://freuds.github.io/custom-charts/imgs/proxy.png
name: proxy
version: 1.1.0
type: application
home: https://freuds.github.io/custom-charts
sources:
  - https://freuds.github.io/custom-charts
keywords:
  - proxy
  - ingress
  - api-gateway
maintainers:
  - name: Freuds
